<img src="http://akhavanpour.ir/notebook/images/srttu.gif" alt="SRTTU" style="width: 150px;"/>

[![Azure Notebooks](https://notebooks.azure.com/launch.png)](https://notebooks.azure.com/import/gh/Alireza-Akhavan/class.vision)

In [1]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [2]:
tf.__version__

'1.11.0'

In [3]:
hello = tf.constant("Hello, TensorFlow!")
sess = tf.Session()
print(sess.run(hello))

b'Hello, TensorFlow!'


In [4]:
node1 = tf.constant(3.0, dtype=tf.float32)
node2 = tf.constant(4.0) # also tf.float32 implicitly

In [5]:
print(node1, node2)

Tensor("Const_1:0", shape=(), dtype=float32) Tensor("Const_2:0", shape=(), dtype=float32)


In [6]:
sess.close()

In [7]:
sess = tf.Session()
print(sess.run([node1, node2]))

[3.0, 4.0]


In [8]:
with tf.Session() as sess:
    a = sess.run([node1, node2])
print(a)

[3.0, 4.0]


In [9]:
with tf.Session() as sess:
    node3 = tf.add(node1, node2 , name='my_add')
    print("node3:", node3)
    print("sess.run(node3):", sess.run(node3))


node3: Tensor("my_add:0", shape=(), dtype=float32)
sess.run(node3): 7.0


<img src="lecture_images/getting_started_add.png" />

# placeholder:

In [10]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b  # + provides a shortcut for tf.add(a, b)

In [11]:
adder_node

<tf.Tensor 'add:0' shape=<unknown> dtype=float32>

In [12]:
sess = tf.Session()
print(sess.run(adder_node, {a: 3, b: 4.5}))
print(sess.run(adder_node, {a: [1, 3], b: [2, 4]}))

7.5
[3. 7.]


<img src="lecture_images/getting_started_adder.png" />

In [13]:
add_and_triple = adder_node * 3.
print(sess.run(add_and_triple, {a: 3, b: 4.5}))

22.5


<img src="lecture_images/getting_started_triple.png" />

# Variable:

In [14]:
W = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)
x = tf.placeholder(tf.float32)
linear_model = W*x + b

Constants are initialized when you call tf.constant, and their value can never change. By contrast, variables are not initialized when you call tf.Variable. To initialize all the variables in a TensorFlow program, you must explicitly call a special operation as follows:

In [15]:
init = tf.global_variables_initializer()
sess.run(init)

In [16]:
print(sess.run(linear_model, {x: [1, 2, 3, 4]}))

[0.         0.3        0.6        0.90000004]


##  Variable Initialization:

In [17]:
W1 = tf.ones((2,2))
W2 = tf.Variable(tf.zeros((2,2)), name="weights")
with tf.Session() as sess:
    print(sess.run(W1))
    sess.run(tf.global_variables_initializer())
    print(sess.run(W2))


[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


# Slide 21

In [18]:
state = tf.Variable(0, name="counter")
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)

In [19]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(update))



1


In [20]:
print(sess.run(update))

2


In [21]:
sess.close()

In [22]:
x = tf.Variable(0, name='counter')
inc = tf.assign_add(x, 1, name='increment')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(5):
        print (sess.run(inc))

1
2
3
4
5


### <div style="text-align: right;direction:rtl;font-family:tahoma">میانگین (tf.reduce_mean)</div>

In [23]:
x = tf.constant([[1.0,2.0], 
                 [3.0,4.0]])

Mean1 = tf.reduce_mean(x)
Mean2 = tf.reduce_mean(x,0)
Mean3 = tf.reduce_mean(x,1)
with tf.Session() as sess:
    result1 = sess.run(Mean1)
    result2 = sess.run(Mean2)
    result3 = sess.run(Mean3)
    
print(result1)
print(result2)
print(result3)


2.5
[2. 3.]
[1.5 3.5]


In [24]:
type(result1)

numpy.float32

### <div style="text-align: right;direction:rtl;font-family:tahoma">ضرب ماترسی (tf.reduce_mean)</div>

In [25]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])


In [26]:
sess = tf.Session()

In [27]:
sess.run(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
sess.run(b)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
c = tf.matmul(a, b)

In [30]:
c

<tf.Tensor 'MatMul:0' shape=(2, 2) dtype=int32>

In [31]:
sess.run(c)

array([[ 58,  64],
       [139, 154]])

In [32]:
d=c+tf.constant([10,2])

In [33]:
sess.run(d)

array([[ 68,  66],
       [149, 156]])

### <div style="text-align: right;direction:rtl;font-family:tahoma">بیشینه گیری (tf.argmax)</div>

In [34]:
x = tf.constant([[1.0,2.0], 
                 [4.0,3.0]])
m1=tf.argmax(x,0)
m2=tf.argmax(x,1)
with tf.Session() as sess:
    r1=sess.run(m1)
    r2=sess.run(m2)
print(r1)
print(r2)

[1 1]
[1 0]


# <div style="text-align: right;direction:rtl;font-family:tahoma">عمل کانولوشن در تنسورفلو<div>

<div style="text-align: right;direction:rtl;font-family:tahoma"> فرض کنید 2 تا تنسور(tensor) به ترتیب زیر داریم: </div>

<div style="font-family:tahoma;">
* 3x3 فیلتر (4D tensor = [3,3,1,1] = [width, height, channels, number of filters])
</div>
<div style="font-family:tahoma;">
* 10x10 تصویر (4D tensor = [1,10,10,1] = [batch size, width, height, number of channels])
</div>

<div style="text-align: right;direction:rtl;font-family:tahoma">خروجی عمل کانولوشن با zero padding :</div>

* the same as input = 10x10

<div style="text-align: right;direction:rtl;font-family:tahoma">خروجی عمل کانولوشن بدون zero padding :</div>

* input size - kernel dimension +1 = 10 -3 + 1 = 8 = 8x8



In [35]:
input = tf.Variable(tf.random_normal([1,10,10,1]))
filter = tf.Variable(tf.random_normal([3,3,1,1]))
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')
op2 = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='SAME')

In [36]:
#Initialization and session
init = tf.global_variables_initializer()
sess=tf.InteractiveSession()
sess.run(init)

In [37]:
print(input.get_shape())
#print(input.eval())

(1, 10, 10, 1)


In [38]:
print(filter.get_shape())
#print(filter.eval())


(3, 3, 1, 1)


In [39]:
result = sess.run(op)
print(result.shape)

(1, 8, 8, 1)


In [40]:
result2 = sess.run(op2)
print(result2.shape)

(1, 10, 10, 1)


<div class="alert alert-block alert-info">
<div style="direction:rtl;text-align:right;font-family:B Lotus, B Nazanin, Tahoma"> دانشگاه تربیت دبیر شهید رجایی<br>مباحث ویژه 2 - یادگیری عمیق پیشرفته<br>علیرضا اخوان پور<br>97-98<br>
</div>
<a href="https://www.srttu.edu/">SRTTU.edu</a> - <a href="http://class.vision">Class.Vision</a> - <a href="http://AkhavanPour.ir">AkhavanPour.ir</a>
</div>